# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Translatewiz"
client_id = "23de71ec6c87b27047a217730584b0d6"
application_url = "https://confirmation-exempt-ron-banners.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://confirmation-exempt-ron-banners.trycloudflare.com/auth/callback",
  "https://confirmation-exempt-ron-banners.trycloudflare.com/auth/shopify/callback",
  "https://confirmation-exempt-ron-banners.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tools-iot.myshopify.com"
